In [22]:
import random
import numpy as np
from scipy.sparse import csr_matrix

# Uniform-random matrix, with given uniform-random sparsity
def spRandUMat(dim, valRange, sparsity, dtype):
    # Compute number of sparse elements
    size1D = dim[0] * dim[1]
    size1Dsparse = int(size1D * sparsity)
    
    # Generate random values
    val = np.random.uniform(valRange[0], valRange[1], size1Dsparse)
    
    # Generate locations of non-zero matrix elements, uniformly distributed over the matrix
    #idx1D = np.random.permutation(size1D)[:size1Dsparse]  # NOTE: this is too memory-hungry for large sizes
    idx1D = np.array(random.sample(range(0, size1D), size1Dsparse))
    
    idx2Drow = idx1D / dim[1]
    idx2Dcol = idx1D % dim[1]
    
    return csr_matrix((val, (idx2Drow, idx2Dcol)), shape=dim, dtype=dtype)

In [32]:
import copy
sp1 = spRandUMat((10, 10), [0, 10], 0.2, dtype=int)
sp2 = copy.deepcopy(sp1)

def clip(spmat):
    spmat[spmat > 5] = 20

clip(sp2)

print(sp1.toarray())
print(sp2.toarray())

# from sklearn.preprocessing import normalize
# bbb = normalize(sp2, axis=1, norm='l1')
# print(bbb.toarray())

[[0 0 1 0 0 7 0 8 0 0]
 [0 0 0 0 8 0 0 0 0 2]
 [0 0 5 0 0 0 0 9 6 0]
 [8 0 0 0 0 4 8 0 8 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 1 0]
 [0 0 0 0 0 0 5 0 0 0]
 [3 0 0 0 0 0 0 0 0 5]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[ 0  0  1  0  0 20  0 20  0  0]
 [ 0  0  0  0 20  0  0  0  0  2]
 [ 0  0  5  0  0  0  0 20 20  0]
 [20  0  0  0  0  4 20  0 20  0]
 [ 0  0  0  0  4  0  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  1  0]
 [ 0  0  0  0  0  0  5  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  5]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [40]:
print(sp2.tocoo().row)
print(sp2.tocoo().col)
print(sp2)

[0 0 0 1 1 1 2 2 2 3 3 3 3 4 5 5 6 7 7 8]
[2 5 7 1 4 9 2 7 8 0 5 6 8 4 6 8 6 0 9 5]
  (0, 2)	1
  (0, 5)	20
  (0, 7)	20
  (1, 1)	0
  (1, 4)	20
  (1, 9)	2
  (2, 2)	5
  (2, 7)	20
  (2, 8)	20
  (3, 0)	20
  (3, 5)	4
  (3, 6)	20
  (3, 8)	20
  (4, 4)	4
  (5, 6)	20
  (5, 8)	1
  (6, 6)	5
  (7, 0)	3
  (7, 9)	5
  (8, 5)	5
